
Running tests... 
----------------------------------------------------------------------
 test_login_1___1____1____False__ (test0.api_test.cases.lksense_login_test.Login_test) ... OK (0.014777)s
 test_login_2___linksense____lksense_2018____True__ (test0.api_test.cases.lksense_login_test.Login_test) ... OK (0.061216)s
 test_login_3___linksense_________False__ (test0.api_test.cases.lksense_login_test.Login_test) ... OK (0.053511)s
 test_login_4___aaa____aaa____True__ (test0.api_test.cases.lksense_login_test.Login_test) ... FAIL (0.006677)s
 test_avi_get (test0.api_test.cases.lksense_avi_get_test.Avi_Get_test) ... OK (0.142072)s
 test_asset_get (test0.api_test.cases.lksense_asset_get_test.Asset_Get_test) ... OK (0.130793)s
 test_asset_average (test0.api_test.cases.lksense_asset_average_test.Asset_Average_test) ... OK (0.607511)s
 test_basic_config (test0.api_test.cases.lksense_basic_vrsconfig_test.Basic_Vrsconfig) ... OK (0.110022)s
 test_change_vrs_result (test0.api_test.cases.lksense_change_vrs_result_test.Change_Vrs_Result_test) ... OK (0.377987)s
 test_config_get (test0.api_test.cases.lksense_config_get_test.Congfig_Get_test) ... OK (0.128766)s
 test_gpu_update (test0.api_test.cases.lksense_gpu_update_test.GPU_Update_test) ... OK (0.350203)s
 test_get_user (test0.api_test.cases.lksense_get_user_test.Get_User_test) ... OK (0.112534)s
 test_gpu_info_get (test0.api_test.cases.lksense_gpu_info_get_test.GPU_Info_Get_test) ... OK (0.121515)s
 test_label (test0.api_test.cases.lksense_label_test.Label_test) ... OK (0.482573)s
 test_machine_data (test0.api_test.cases.lksense_machine_data_test.Machine_Data_test) ... OK (0.154080)s
 test_machine_manage (test0.api_test.cases.lksense_machine_manage_test.Machine_manage_test) ... OK (1.040771)s
 test_ngdata_get (test0.api_test.cases.lksense_ngdata_get_test.Ngdata_Get_test) ... OK (0.357862)s
 test_page_permission (test0.api_test.cases.lksense_page_permission_test.Page_Permission_test) ... OK (0.073269)s
 test_stack_data (test0.api_test.cases.lksense_stack_data_test.Stack_Data_test) ... OK (0.395741)s
 test_point (test0.api_test.cases.lksense_turn_page_test.Turn_Page_test) ... OK (0.359260)s
 test_turn_page (test0.api_test.cases.lksense_turn_page_test.Turn_Page_test) ... OK (0.149356)s

======================================================================
FAIL [0.006677s]: test0.api_test.cases.lksense_login_test.Login_test.test_login_4___aaa____aaa____True__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Python38-32\lib\site-packages\ddt.py", line 220, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Python38-32\Scripts\lk_test\test0\api_test\cases\lksense_login_test.py", line 31, in test_login
    self.assertEqual(str(res.json()['success']),expected_result,'µÇÂ¼Ê§°Ü£¬²âÊÔ²»Í¨¹ı£¡')
AssertionError: 'False' != 'True'
- False
+ True
 : µÇÂ¼Ê§°Ü£¬²âÊÔ²»Í¨¹ı£¡

----------------------------------------------------------------------
Ran 21 tests in 0:00:05

FAILED
 (Failures=1)

Generating HTML reports... 
reports\lk_api_test_2023-05-25_18-33-03.html
